// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ui.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Action is the list of actions sent or received via the Notifications channel.
type Action int32

const (
	Action_NONE                 Action = 0
	Action_ENABLE_INTERCEPTION  Action = 1
	Action_DISABLE_INTERCEPTION Action = 2
	Action_ENABLE_FIREWALL      Action = 3
	Action_DISABLE_FIREWALL     Action = 4
	Action_RELOAD_FW_RULES      Action = 5
	Action_CHANGE_CONFIG        Action = 6
	Action_ENABLE_RULE          Action = 7
	Action_DISABLE_RULE         Action = 8
	Action_DELETE_RULE          Action = 9
	Action_CHANGE_RULE          Action = 10
	Action_LOG_LEVEL            Action = 11
	Action_STOP                 Action = 12
	// Notifications of type TASK_START or TASK_STOP expect a JSON in the
	// Notification.data field.
	// It's parsed to a struct with format
	// TaskNotification { Name string, Data interface{} }
	// where Data is translated to a map of values (map[string]string), with
	// the configuration for each task:
	// PidMonitor: {"interval": "5s", "pid": "1234"}
	// SocketsMonitor: {"interval": "5s", "states": "1,10"}
	Action_TASK_START Action = 13
	Action_TASK_STOP  Action = 14
)

var Action_name = map[int32]string{
	0:  "NONE",
	1:  "ENABLE_INTERCEPTION",
	2:  "DISABLE_INTERCEPTION",
	3:  "ENABLE_FIREWALL",
	4:  "DISABLE_FIREWALL",
	5:  "RELOAD_FW_RULES",
	6:  "CHANGE_CONFIG",
	7:  "ENABLE_RULE",
	8:  "DISABLE_RULE",
	9:  "DELETE_RULE",
	10: "CHANGE_RULE",
	11: "LOG_LEVEL",
	12: "STOP",
	13: "TASK_START",
	14: "TASK_STOP",
}

var Action_value = map[string]int32{
	"NONE":                 0,
	"ENABLE_INTERCEPTION":  1,
	"DISABLE_INTERCEPTION": 2,
	"ENABLE_FIREWALL":      3,
	"DISABLE_FIREWALL":     4,
	"RELOAD_FW_RULES":      5,
	"CHANGE_CONFIG":        6,
	"ENABLE_RULE":          7,
	"DISABLE_RULE":         8,
	"DELETE_RULE":          9,
	"CHANGE_RULE":          10,
	"LOG_LEVEL":            11,
	"STOP":                 12,
	"TASK_START":           13,
	"TASK_STOP":            14,
}

func (x Action) String() string {
	return proto.EnumName(Action_name, int32(x))
}

func (Action) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_63867a62624c1283, []int{0}
}

type NotificationReplyCode int32

const (
	NotificationReplyCode_OK    NotificationReplyCode = 0
	NotificationReplyCode_ERROR NotificationReplyCode = 1
)

var NotificationReplyCode_name = map[int32]string{
	0: "OK",
	1: "ERROR",
}

var NotificationReplyCode_value = map[string]int32{
	"OK":    0,
	"ERROR": 1,
}

func (x NotificationReplyCode) String() string {
	return proto.EnumName(NotificationReplyCode_name, int32(x))
}

func (NotificationReplyCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_63867a62624c1283, []int{1}
}

type Alert_Priority int32

const (
	Alert_LOW    Alert_Priority = 0
	Alert_MEDIUM Alert_Priority = 1
	Alert_HIGH   Alert_Priority = 2
)

var Alert_Priority_name = map[int32]string{
	0: "LOW",
	1: "MEDIUM",
	2: "HIGH",
}

var Alert_Priority_value = map[string]int32{
	"LOW":    0,
	"MEDIUM": 1,
	"HIGH":   2,
}

func (x Alert_Priority) String() string {
	return proto.EnumName(Alert_Priority_name, int32(x))
}

func (Alert_Priority) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_63867a62624c1283, []int{0, 0}
}

type Alert_Type int32

const (
	Alert_ERROR   Alert_Type = 0
	Alert_WARNING Alert_Type = 1
	Alert_INFO    Alert_Type = 2
)

var Alert_Type_name = map[int32]string{
	0: "ERROR",
	1: "WARNING",
	2: "INFO",
}

var Alert_Type_value = map[string]int32{
	"ERROR":   0,
	"WARNING": 1,
	"INFO":    2,
}

func (x Alert_Type) String() string {
	return proto.EnumName(Alert_Type_name, int32(x))
}

func (Alert_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_63867a62624c1283, []int{0, 1}
}

type Alert_Action int32

const (
	Alert_NONE       Alert_Action = 0
	Alert_SHOW_ALERT Alert_Action = 1
	Alert_SAVE_TO_DB Alert_Action = 2
)

var Alert_Action_name = map[int32]string{
	0: "NONE",
	1: "SHOW_ALERT",
	2: "SAVE_TO_DB",
}

var Alert_Action_value = map[string]int32{
	"NONE":       0,
	"SHOW_ALERT": 1,
	"SAVE_TO_DB": 2,
}

func (x Alert_Action) String() string {
	return proto.EnumName(Alert_Action_name, int32(x))
}

func (Alert_Action) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_63867a62624c1283, []int{0, 2}
}

// What caused the alert
type Alert_What int32

const (
	Alert_GENERIC      Alert_What = 0
	Alert_PROC_MONITOR Alert_What = 1
	Alert_FIREWALL     Alert_What = 2
	Alert_CONNECTION   Alert_What = 3
	Alert_RULE         Alert_What = 4
	Alert_NETLINK      Alert_What = 5
	// bind, exec, etc
	Alert_KERNEL_EVENT Alert_What = 6
)

var Alert_What_name = map[int32]string{
	0: "GENERIC",
	1: "PROC_MONITOR",
	2: "FIREWALL",
	3: "CONNECTION",
	4: "RULE",
	5: "NETLINK",
	6: "KERNEL_EVENT",
}

var Alert_What_value = map[string]int32{
	"GENERIC":      0,
	"PROC_MONITOR": 1,
	"FIREWALL":     2,
	"CONNECTION":   3,
	"RULE":         4,
	"NETLINK":      5,
	"KERNEL_EVENT": 6,
}

func (x Alert_What) String() string {
	return proto.EnumName(Alert_What_name, int32(x))
}

func (Alert_What) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_63867a62624c1283, []int{0, 3}
}

// *
// - Send error messages (kernel not compatible, etc)
// - Send warnings (eBPF modules failed loading, etc)
// - Send kernel events: new execs, bytes recv/sent, ...
// - Alert of events defined by the user: alert when a rule matches
type Alert struct {
	Id   uint64     `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type Alert_Type `protobuf:"varint,2,opt,name=type,proto3,enum=protocol.Alert_Type" json:"type,omitempty"`
	// TODO: group of actions: SHOW_ALERT | SAVE_TO_DB
	Action   Alert_Action   `protobuf:"varint,3,opt,name=action,proto3,enum=protocol.Alert_Action" json:"action,omitempty"`
	Priority Alert_Priority `protobuf:"varint,4,opt,name=priority,proto3,enum=protocol.Alert_Priority" json:"priority,omitempty"`
	What     Alert_What     `protobuf:"varint,5,opt,name=what,proto3,enum=protocol.Alert_What" json:"what,omitempty"`
	// https://developers.google.com/protocol-buffers/docs/reference/go-generated#oneof
	//
	// Types that are valid to be assigned to Data:
	//
	//	*Alert_Text
	//	*Alert_Proc
	//	*Alert_Conn
	//	*Alert_Rule
	//	*Alert_Fwrule
	Data                 isAlert_Data `protobuf_oneof:"data"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Alert) Reset()         { *m = Alert{} }
func (m *Alert) String() string { return proto.CompactTextString(m) }
func (*Alert) ProtoMessage()    {}
func (*Alert) Descriptor() ([]byte, []int) {
	return fileDescriptor_63867a62624c1283, []int{0}
}

func (m *Alert) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Alert.Unmarshal(m, b)
}
func (m *Alert) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Alert.Marshal(b, m, deterministic)
}
func (m *Alert) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Alert.Merge(m, src)
}
func (m *Alert) XXX_Size() int {
	return xxx_messageInfo_Alert.Size(m)
}
func (m *Alert) XXX_DiscardUnknown() {
	xxx_messageInfo_Alert.DiscardUnknown(m)
}

var xxx_messageInfo_Alert proto.InternalMessageInfo

func (m *Alert) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Alert) GetType() Alert_Type {
	if m != nil {
		return m.Type
	}
	return Alert_ERROR
}

func (m *Alert) GetAction() Alert_Action {
	if m != nil {
		return m.Action
	}
	return Alert_NONE
}

func (m *Alert) GetPriority() Alert_Priority {
	if m != nil {
		return m.Priority
	}
	return Alert_LOW
}

func (m *Alert) GetWhat() Alert_What {
	if m != nil {
		return m.What
	}
	return Alert_GENERIC
}

type isAlert_Data interface {
	isAlert_Data()
}

type Alert_Text struct {
	Text string `protobuf:"bytes,6,opt,name=text,proto3,oneof"`
}

type Alert_Proc struct {
	Proc *Process `protobuf:"bytes,8,opt,name=proc,proto3,oneof"`
}

type Alert_Conn struct {
	Conn *Connection `protobuf:"bytes,9,opt,name=conn,proto3,oneof"`
}

type Alert_Rule struct {
	Rule *Rule `protobuf:"bytes,10,opt,name=rule,proto3,oneof"`
}

type Alert_Fwrule struct {
	Fwrule *FwRule `protobuf:"bytes,11,opt,name=fwrule,proto3,oneof"`
}

func (*Alert_Text) isAlert_Data() {}

func (*Alert_Proc) isAlert_Data() {}

func (*Alert_Conn) isAlert_Data() {}

func (*Alert_Rule) isAlert_Data() {}

func (*Alert_Fwrule) isAlert_Data() {}

func (m *Alert) GetData() isAlert_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Alert) GetText() string {
	if x, ok := m.GetData().(*Alert_Text); ok {
		return x.Text
	}
	return ""
}

func (m *Alert) GetProc() *Process {
	if x, ok := m.GetData().(*Alert_Proc); ok {
		return x.Proc
	}
	return nil
}

func (m *Alert) GetConn() *Connection {
	if x, ok := m.GetData().(*Alert_Conn); ok {
		return x.Conn
	}
	return nil
}

func (m *Alert) GetRule() *Rule {
	if x, ok := m.GetData().(*Alert_Rule); ok {
		return x.Rule
	}
	return nil
}

func (m *Alert) GetFwrule() *FwRule {
	if x, ok := m.GetData().(*Alert_Fwrule); ok {
		return x.Fwrule
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Alert) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Alert_Text)(nil),
		(*Alert_Proc)(nil),
		(*Alert_Conn)(nil),
		(*Alert_Rule)(nil),
		(*Alert_Fwrule)(nil),
	}
}

type MsgResponse struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgResponse) Reset()         { *m = MsgResponse{} }
func (m *MsgResponse) String() string { return proto.CompactTextString(m) }
func (*MsgResponse) ProtoMessage()    {}
func (*MsgResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_63867a62624c1283, []int{1}
}

func (m *MsgResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgResponse.Unmarshal(m, b)
}
func (m *MsgResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgResponse.Marshal(b, m, deterministic)
}
func (m *MsgResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgResponse.Merge(m, src)
}
func (m *MsgResponse) XXX_Size() int {
	return xxx_messageInfo_MsgResponse.Size(m)
}
func (m *MsgResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgResponse proto.InternalMessageInfo

func (m *MsgResponse) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type Event struct {
	Time                 string      `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	Connection           *Connection `protobuf:"bytes,2,opt,name=connection,proto3" json:"connection,omitempty"`
	Rule                 *Rule       `protobuf:"bytes,3,opt,name=rule,proto3" json:"rule,omitempty"`
	Unixnano             int64       `protobuf:"varint,4,opt,name=unixnano,proto3" json:"unixnano,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_63867a62624c1283, []int{2}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func (m *Event) GetConnection() *Connection {
	if m != nil {
		return m.Connection
	}
	return nil
}

func (m *Event) GetRule() *Rule {
	if m != nil {
		return m.Rule
	}
	return nil
}

func (m *Event) GetUnixnano() int64 {
	if m != nil {
		return m.Unixnano
	}
	return 0
}

type Statistics struct {
	DaemonVersion        string            `protobuf:"bytes,1,opt,name=daemon_version,json=daemonVersion,proto3" json:"daemon_version,omitempty"`
	Rules                uint64            `protobuf:"varint,2,opt,name=rules,proto3" json:"rules,omitempty"`
	Uptime               uint64            `protobuf:"varint,3,opt,name=uptime,proto3" json:"uptime,omitempty"`
	DnsResponses         uint64            `protobuf:"varint,4,opt,name=dns_responses,json=dnsResponses,proto3" json:"dns_responses,omitempty"`
	Connections          uint64            `protobuf:"varint,5,opt,name=connections,proto3" json:"connections,omitempty"`
	Ignored              uint64            `protobuf:"varint,6,opt,name=ignored,proto3" json:"ignored,omitempty"`
	Accepted             uint64            `protobuf:"varint,7,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Dropped              uint64            `protobuf:"varint,8,opt,name=dropped,proto3" json:"dropped,omitempty"`
	RuleHits             uint64            `protobuf:"varint,9,opt,name=rule_hits,json=ruleHits,proto3" json:"rule_hits,omitempty"`
	RuleMisses           uint64            `protobuf:"varint,10,opt,name=rule_misses,json=ruleMisses,proto3" json:"rule_misses,omitempty"`
	ByProto              map[string]uint64 `protobuf:"bytes,11,rep,name=by_proto,json=byProto,proto3" json:"by_proto,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	ByAddress            map[string]uint64 `protobuf:"bytes,12,rep,name=by_address,json=byAddress,proto3" json:"by_address,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	ByHost               map[string]uint64 `protobuf:"bytes,13,rep,name=by_host,json=byHost,proto3" json:"by_host,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	ByPort               map[string]uint64 `protobuf:"bytes,14,rep,name=by_port,json=byPort,proto3" json:"by_port,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	ByUid                map[string]uint64 `protobuf:"bytes,15,rep,name=by_uid,json=byUid,proto3" json:"by_uid,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	ByExecutable         map[string]uint64 `protobuf:"bytes,16,rep,name=by_executable,json=byExecutable,proto3" json:"by_executable,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	Events               []*Event          `protobuf:"bytes,17,rep,name=events,proto3" json:"events,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Statistics) Reset()         { *m = Statistics{} }
func (m *Statistics) String() string { return proto.CompactTextString(m) }
func (*Statistics) ProtoMessage()    {}
func (*Statistics) Descriptor() ([]byte, []int) {
	return fileDescriptor_63867a62624c1283, []int{3}
}

func (m *Statistics) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Statistics.Unmarshal(m, b)
}
func (m *Statistics) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Statistics.Marshal(b, m, deterministic)
}
func (m *Statistics) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Statistics.Merge(m, src)
}
func (m *Statistics) XXX_Size() int {
	return xxx_messageInfo_Statistics.Size(m)
}
func (m *Statistics) XXX_DiscardUnknown() {
	xxx_messageInfo_Statistics.DiscardUnknown(m)
}

var xxx_messageInfo_Statistics proto.InternalMessageInfo

func (m *Statistics) GetDaemonVersion() string {
	if m != nil {
		return m.DaemonVersion
	}
	return ""
}

func (m *Statistics) GetRules() uint64 {
	if m != nil {
		return m.Rules
	}
	return 0
}

func (m *Statistics) GetUptime() uint64 {
	if m != nil {
		return m.Uptime
	}
	return 0
}

func (m *Statistics) GetDnsResponses() uint64 {
	if m != nil {
		return m.DnsResponses
	}
	return 0
}

func (m *Statistics) GetConnections() uint64 {
	if m != nil {
		return m.Connections
	}
	return 0
}

func (m *Statistics) GetIgnored() uint64 {
	if m != nil {
		return m.Ignored
	}
	return 0
}

func (m *Statistics) GetAccepted() uint64 {
	if m != nil {
		return m.Accepted
	}
	return 0
}

func (m *Statistics) GetDropped() uint64 {
	if m != nil {
		return m.Dropped
	}
	return 0
}

func (m *Statistics) GetRuleHits() uint64 {
	if m != nil {
		return m.RuleHits
	}
	return 0
}

func (m *Statistics) GetRuleMisses() uint64 {
	if m != nil {
		return m.RuleMisses
	}
	return 0
}

func (m *Statistics) GetByProto() map[string]uint64 {
	if m != nil {
		return m.ByProto
	}
	return nil
}

func (m *Statistics) GetByAddress() map[string]uint64 {
	if m != nil {
		return m.ByAddress
	}
	return nil
}

func (m *Statistics) GetByHost() map[string]uint64 {
	if m != nil {
		return m.ByHost
	}
	return nil
}

func (m *Statistics) GetByPort() map[string]uint64 {
	if m != nil {
		return m.ByPort
	}
	return nil
}

func (m *Statistics) GetByUid() map[string]uint64 {
	if m != nil {
		return m.ByUid
	}
	return nil
}

func (m *Statistics) GetByExecutable() map[string]uint64 {
	if m != nil {
		return m.ByExecutable
	}
	return nil
}

func (m *Statistics) GetEvents() []*Event {
	if m != nil {
		return m.Events
	}
	return nil
}

type PingRequest struct {
	Id                   uint64      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Stats                *Statistics `protobuf:"bytes,2,opt,name=stats,proto3" json:"stats,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PingRequest) Reset()         { *m = PingRequest{} }
func (m *PingRequest) String() string { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()    {}
func (*PingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_63867a62624c1283, []int{4}
}

func (m *PingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingRequest.Unmarshal(m, b)
}
func (m *PingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingRequest.Marshal(b, m, deterministic)
}
func (m *PingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingRequest.Merge(m, src)
}
func (m *PingRequest) XXX_Size() int {
	return xxx_messageInfo_PingRequest.Size(m)
}
func (m *PingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PingRequest proto.InternalMessageInfo

func (m *PingRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PingRequest) GetStats() *Statistics {
	if m != nil {
		return m.Stats
	}
	return nil
}

type PingReply struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingReply) Reset()         { *m = PingReply{} }
func (m *PingReply) String() string { return proto.CompactTextString(m) }
func (*PingReply) ProtoMessage()    {}
func (*PingReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_63867a62624c1283, []int{5}
}

func (m *PingReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingReply.Unmarshal(m, b)
}
func (m *PingReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingReply.Marshal(b, m, deterministic)
}
func (m *PingReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingReply.Merge(m, src)
}
func (m *PingReply) XXX_Size() int {
	return xxx_messageInfo_PingReply.Size(m)
}
func (m *PingReply) XXX_DiscardUnknown() {
	xxx_messageInfo_PingReply.DiscardUnknown(m)
}

var xxx_messageInfo_PingReply proto.InternalMessageInfo

func (m *PingReply) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type StringInt struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                uint32   `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StringInt) Reset()         { *m = StringInt{} }
func (m *StringInt) String() string { return proto.CompactTextString(m) }
func (*StringInt) ProtoMessage()    {}
func (*StringInt) Descriptor() ([]byte, []int) {
	return fileDescriptor_63867a62624c1283, []int{6}
}

func (m *StringInt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringInt.Unmarshal(m, b)
}
func (m *StringInt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringInt.Marshal(b, m, deterministic)
}
func (m *StringInt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringInt.Merge(m, src)
}
func (m *StringInt) XXX_Size() int {
	return xxx_messageInfo_StringInt.Size(m)
}
func (m *StringInt) XXX_DiscardUnknown() {
	xxx_messageInfo_StringInt.DiscardUnknown(m)
}

var xxx_messageInfo_StringInt proto.InternalMessageInfo

func (m *StringInt) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *StringInt) GetValue() uint32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type Process struct {
	Pid                  uint64            `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Ppid                 uint64            `protobuf:"varint,2,opt,name=ppid,proto3" json:"ppid,omitempty"`
	Uid                  uint64            `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`
	Comm                 string            `protobuf:"bytes,4,opt,name=comm,proto3" json:"comm,omitempty"`
	Path                 string            `protobuf:"bytes,5,opt,name=path,proto3" json:"path,omitempty"`
	Args                 []string          `protobuf:"bytes,6,rep,name=args,proto3" json:"args,omitempty"`
	Env                  map[string]string `protobuf:"bytes,7,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Cwd                  string            `protobuf:"bytes,8,opt,name=cwd,proto3" json:"cwd,omitempty"`
	Checksums            map[string]string `protobuf:"bytes,9,rep,name=checksums,proto3" json:"checksums,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	IoReads              uint64            `protobuf:"varint,10,opt,name=io_reads,json=ioReads,proto3" json:"io_reads,omitempty"`
	IoWrites             uint64            `protobuf:"varint,11,opt,name=io_writes,json=ioWrites,proto3" json:"io_writes,omitempty"`
	NetReads             uint64            `protobuf:"varint,12,opt,name=net_reads,json=netReads,proto3" json:"net_reads,omitempty"`
	NetWrites            uint64            `protobuf:"varint,13,opt,name=net_writes,json=netWrites,proto3" json:"net_writes,omitempty"`
	ProcessTree          []*StringInt      `protobuf:"bytes,14,rep,name=process_tree,json=processTree,proto3" json:"process_tree,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Process) Reset()         { *m = Process{} }
func (m *Process) String() string { return proto.CompactTextString(m) }
func (*Process) ProtoMessage()    {}
func (*Process) Descriptor() ([]byte, []int) {
	return fileDescriptor_63867a62624c1283, []int{7}
}

func (m *Process) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Process.Unmarshal(m, b)
}
func (m *Process) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Process.Marshal(b, m, deterministic)
}
func (m *Process) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Process.Merge(m, src)
}
func (m *Process) XXX_Size() int {
	return xxx_messageInfo_Process.Size(m)
}
func (m *Process) XXX_DiscardUnknown() {
	xxx_messageInfo_Process.DiscardUnknown(m)
}

var xxx_messageInfo_Process proto.InternalMessageInfo

func (m *Process) GetPid() uint64 {
	if m != nil {
		return m.Pid
	}
	return 0
}

func (m *Process) GetPpid() uint64 {
	if m != nil {
		return m.Ppid
	}
	return 0
}

func (m *Process) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *Process) GetComm() string {
	if m != nil {
		return m.Comm
	}
	return ""
}

func (m *Process) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Process) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *Process) GetEnv() map[string]string {
	if m != nil {
		return m.Env
	}
	return nil
}

func (m *Process) GetCwd() string {
	if m != nil {
		return m.Cwd
	}
	return ""
}

func (m *Process) GetChecksums() map[string]string {
	if m != nil {
		return m.Checksums
	}
	return nil
}

func (m *Process) GetIoReads() uint64 {
	if m != nil {
		return m.IoReads
	}
	return 0
}

func (m *Process) GetIoWrites() uint64 {
	if m != nil {
		return m.IoWrites
	}
	return 0
}

func (m *Process) GetNetReads() uint64 {
	if m != nil {
		return m.NetReads
	}
	return 0
}

func (m *Process) GetNetWrites() uint64 {
	if m != nil {
		return m.NetWrites
	}
	return 0
}

func (m *Process) GetProcessTree() []*StringInt {
	if m != nil {
		return m.ProcessTree
	}
	return nil
}

type Connection struct {
	Protocol             string            `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	SrcIp                string            `protobuf:"bytes,2,opt,name=src_ip,json=srcIp,proto3" json:"src_ip,omitempty"`
	SrcPort              uint32            `protobuf:"varint,3,opt,name=src_port,json=srcPort,proto3" json:"src_port,omitempty"`
	DstIp                string            `protobuf:"bytes,4,opt,name=dst_ip,json=dstIp,proto3" json:"dst_ip,omitempty"`
	DstHost              string            `protobuf:"bytes,5,opt,name=dst_host,json=dstHost,proto3" json:"dst_host,omitempty"`
	DstPort              uint32            `protobuf:"varint,6,opt,name=dst_port,json=dstPort,proto3" json:"dst_port,omitempty"`
	UserId               uint32            `protobuf:"varint,7,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProcessId            uint32            `protobuf:"varint,8,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	ProcessPath          string            `protobuf:"bytes,9,opt,name=process_path,json=processPath,proto3" json:"process_path,omitempty"`
	ProcessCwd           string            `protobuf:"bytes,10,opt,name=process_cwd,json=processCwd,proto3" json:"process_cwd,omitempty"`
	ProcessArgs          []string          `protobuf:"bytes,11,rep,name=process_args,json=processArgs,proto3" json:"process_args,omitempty"`
	ProcessEnv           map[string]string `protobuf:"bytes,12,rep,name=process_env,json=processEnv,proto3" json:"process_env,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	ProcessChecksums     map[string]string `protobuf:"bytes,13,rep,name=process_checksums,json=processChecksums,proto3" json:"process_checksums,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	ProcessTree          []*StringInt      `protobuf:"bytes,14,rep,name=process_tree,json=processTree,proto3" json:"process_tree,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Connection) Reset()         { *m = Connection{} }
func (m *Connection) String() string { return proto.CompactTextString(m) }
func (*Connection) ProtoMessage()    {}
func (*Connection) Descriptor() ([]byte, []int) {
	return fileDescriptor_63867a62624c1283, []int{8}
}

func (m *Connection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Connection.Unmarshal(m, b)
}
func (m *Connection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Connection.Marshal(b, m, deterministic)
}
func (m *Connection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Connection.Merge(m, src)
}
func (m *Connection) XXX_Size() int {
	return xxx_messageInfo_Connection.Size(m)
}
func (m *Connection) XXX_DiscardUnknown() {
	xxx_messageInfo_Connection.DiscardUnknown(m)
}

var xxx_messageInfo_Connection proto.InternalMessageInfo

func (m *Connection) GetProtocol() string {
	if m != nil {
		return m.Protocol
	}
	return ""
}

func (m *Connection) GetSrcIp() string {
	if m != nil {
		return m.SrcIp
	}
	return ""
}

func (m *Connection) GetSrcPort() uint32 {
	if m != nil {
		return m.SrcPort
	}
	return 0
}

func (m *Connection) GetDstIp() string {
	if m != nil {
		return m.DstIp
	}
	return ""
}

func (m *Connection) GetDstHost() string {
	if m != nil {
		return m.DstHost
	}
	return ""
}

func (m *Connection) GetDstPort() uint32 {
	if m != nil {
		return m.DstPort
	}
	return 0
}

func (m *Connection) GetUserId() uint32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Connection) GetProcessId() uint32 {
	if m != nil {
		return m.ProcessId
	}
	return 0
}

func (m *Connection) GetProcessPath() string {
	if m != nil {
		return m.ProcessPath
	}
	return ""
}

func (m *Connection) GetProcessCwd() string {
	if m != nil {
		return m.ProcessCwd
	}
	return ""
}

func (m *Connection) GetProcessArgs() []string {
	if m != nil {
		return m.ProcessArgs
	}
	return nil
}

func (m *Connection) GetProcessEnv() map[string]string {
	if m != nil {
		return m.ProcessEnv
	}
	return nil
}

func (m *Connection) GetProcessChecksums() map[string]string {
	if m != nil {
		return m.ProcessChecksums
	}
	return nil
}

func (m *Connection) GetProcessTree() []*StringInt {
	if m != nil {
		return m.ProcessTree
	}
	return nil
}

type Operator struct {
	Type                 string      `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Operand              string      `protobuf:"bytes,2,opt,name=operand,proto3" json:"operand,omitempty"`
	Data                 string      `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Sensitive            bool        `protobuf:"varint,4,opt,name=sensitive,proto3" json:"sensitive,omitempty"`
	List                 []*Operator `protobuf:"bytes,5,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Operator) Reset()         { *m = Operator{} }
func (m *Operator) String() string { return proto.CompactTextString(m) }
func (*Operator) ProtoMessage()    {}
func (*Operator) Descriptor() ([]byte, []int) {
	return fileDescriptor_63867a62624c1283, []int{9}
}

func (m *Operator) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Operator.Unmarshal(m, b)
}
func (m *Operator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Operator.Marshal(b, m, deterministic)
}
func (m *Operator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Operator.Merge(m, src)
}
func (m *Operator) XXX_Size() int {
	return xxx_messageInfo_Operator.Size(m)
}
func (m *Operator) XXX_DiscardUnknown() {
	xxx_messageInfo_Operator.DiscardUnknown(m)
}

var xxx_messageInfo_Operator proto.InternalMessageInfo

func (m *Operator) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Operator) GetOperand() string {
	if m != nil {
		return m.Operand
	}
	return ""
}

func (m *Operator) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *Operator) GetSensitive() bool {
	if m != nil {
		return m.Sensitive
	}
	return false
}

func (m *Operator) GetList() []*Operator {
	if m != nil {
		return m.List
	}
	return nil
}

type Rule struct {
	Created              int64     `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`
	Name                 string    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string    `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Enabled              bool      `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Precedence           bool      `protobuf:"varint,5,opt,name=precedence,proto3" json:"precedence,omitempty"`
	Nolog                bool      `protobuf:"varint,6,opt,name=nolog,proto3" json:"nolog,omitempty"`
	Action               string    `protobuf:"bytes,7,opt,name=action,proto3" json:"action,omitempty"`
	Duration             string    `protobuf:"bytes,8,opt,name=duration,proto3" json:"duration,omitempty"`
	Operator             *Operator `protobuf:"bytes,9,opt,name=operator,proto3" json:"operator,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Rule) Reset()         { *m = Rule{} }
func (m *Rule) String() string { return proto.CompactTextString(m) }
func (*Rule) ProtoMessage()    {}
func (*Rule) Descriptor() ([]byte, []int) {
	return fileDescriptor_63867a62624c1283, []int{10}
}

func (m *Rule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rule.Unmarshal(m, b)
}
func (m *Rule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rule.Marshal(b, m, deterministic)
}
func (m *Rule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rule.Merge(m, src)
}
func (m *Rule) XXX_Size() int {
	return xxx_messageInfo_Rule.Size(m)
}
func (m *Rule) XXX_DiscardUnknown() {
	xxx_messageInfo_Rule.DiscardUnknown(m)
}

var xxx_messageInfo_Rule proto.InternalMessageInfo

func (m *Rule) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *Rule) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Rule) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Rule) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *Rule) GetPrecedence() bool {
	if m != nil {
		return m.Precedence
	}
	return false
}

func (m *Rule) GetNolog() bool {
	if m != nil {
		return m.Nolog
	}
	return false
}

func (m *Rule) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *Rule) GetDuration() string {
	if m != nil {
		return m.Duration
	}
	return ""
}

func (m *Rule) GetOperator() *Operator {
	if m != nil {
		return m.Operator
	}
	return nil
}

type StatementValues struct {
	Key                  string   `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatementValues) Reset()         { *m = StatementValues{} }
func (m *StatementValues) String() string { return proto.CompactTextString(m) }
func (*StatementValues) ProtoMessage()    {}
func (*StatementValues) Descriptor() ([]byte, []int) {
	return fileDescriptor_63867a62624c1283, []int{11}
}

func (m *StatementValues) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatementValues.Unmarshal(m, b)
}
func (m *StatementValues) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatementValues.Marshal(b, m, deterministic)
}
func (m *StatementValues) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatementValues.Merge(m, src)
}
func (m *StatementValues) XXX_Size() int {
	return xxx_messageInfo_StatementValues.Size(m)
}
func (m *StatementValues) XXX_DiscardUnknown() {
	xxx_messageInfo_StatementValues.DiscardUnknown(m)
}

var xxx_messageInfo_StatementValues proto.InternalMessageInfo

func (m *StatementValues) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *StatementValues) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Statement struct {
	Op                   string             `protobuf:"bytes,1,opt,name=Op,proto3" json:"Op,omitempty"`
	Name                 string             `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Values               []*StatementValues `protobuf:"bytes,3,rep,name=Values,proto3" json:"Values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Statement) Reset()         { *m = Statement{} }
func (m *Statement) String() string { return proto.CompactTextString(m) }
func (*Statement) ProtoMessage()    {}
func (*Statement) Descriptor() ([]byte, []int) {
	return fileDescriptor_63867a62624c1283, []int{12}
}

func (m *Statement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Statement.Unmarshal(m, b)
}
func (m *Statement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Statement.Marshal(b, m, deterministic)
}
func (m *Statement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Statement.Merge(m, src)
}
func (m *Statement) XXX_Size() int {
	return xxx_messageInfo_Statement.Size(m)
}
func (m *Statement) XXX_DiscardUnknown() {
	xxx_messageInfo_Statement.DiscardUnknown(m)
}

var xxx_messageInfo_Statement proto.InternalMessageInfo

func (m *Statement) GetOp() string {
	if m != nil {
		return m.Op
	}
	return ""
}

func (m *Statement) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Statement) GetValues() []*StatementValues {
	if m != nil {
		return m.Values
	}
	return nil
}

type Expressions struct {
	Statement            *Statement `protobuf:"bytes,1,opt,name=Statement,proto3" json:"Statement,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Expressions) Reset()         { *m = Expressions{} }
func (m *Expressions) String() string { return proto.CompactTextString(m) }
func (*Expressions) ProtoMessage()    {}
func (*Expressions) Descriptor() ([]byte, []int) {
	return fileDescriptor_63867a62624c1283, []int{13}
}

func (m *Expressions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Expressions.Unmarshal(m, b)
}
func (m *Expressions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Expressions.Marshal(b, m, deterministic)
}
func (m *Expressions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Expressions.Merge(m, src)
}
func (m *Expressions) XXX_Size() int {
	return xxx_messageInfo_Expressions.Size(m)
}
func (m *Expressions) XXX_DiscardUnknown() {
	xxx_messageInfo_Expressions.DiscardUnknown(m)
}

var xxx_messageInfo_Expressions proto.InternalMessageInfo

func (m *Expressions) GetStatement() *Statement {
	if m != nil {
		return m.Statement
	}
	return nil
}

type FwRule struct {
	// DEPRECATED: for backward compatibility with iptables
	Table                string         `protobuf:"bytes,1,opt,name=Table,proto3" json:"Table,omitempty"`
	Chain                string         `protobuf:"bytes,2,opt,name=Chain,proto3" json:"Chain,omitempty"`
	UUID                 string         `protobuf:"bytes,3,opt,name=UUID,proto3" json:"UUID,omitempty"`
	Enabled              bool           `protobuf:"varint,4,opt,name=Enabled,proto3" json:"Enabled,omitempty"`
	Position             uint64         `protobuf:"varint,5,opt,name=Position,proto3" json:"Position,omitempty"`
	Description          string         `protobuf:"bytes,6,opt,name=Description,proto3" json:"Description,omitempty"`
	Parameters           string         `protobuf:"bytes,7,opt,name=Parameters,proto3" json:"Parameters,omitempty"`
	Expressions          []*Expressions `protobuf:"bytes,8,rep,name=Expressions,proto3" json:"Expressions,omitempty"`
	Target               string         `protobuf:"bytes,9,opt,name=Target,proto3" json:"Target,omitempty"`
	TargetParameters     string         `protobuf:"bytes,10,opt,name=TargetParameters,proto3" json:"TargetParameters,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *FwRule) Reset()         { *m = FwRule{} }
func (m *FwRule) String() string { return proto.CompactTextString(m) }
func (*FwRule) ProtoMessage()    {}
func (*FwRule) Descriptor() ([]byte, []int) {
	return fileDescriptor_63867a62624c1283, []int{14}
}

func (m *FwRule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FwRule.Unmarshal(m, b)
}
func (m *FwRule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FwRule.Marshal(b, m, deterministic)
}
func (m *FwRule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FwRule.Merge(m, src)
}
func (m *FwRule) XXX_Size() int {
	return xxx_messageInfo_FwRule.Size(m)
}
func (m *FwRule) XXX_DiscardUnknown() {
	xxx_messageInfo_FwRule.DiscardUnknown(m)
}

var xxx_messageInfo_FwRule proto.InternalMessageInfo

func (m *FwRule) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

func (m *FwRule) GetChain() string {
	if m != nil {
		return m.Chain
	}
	return ""
}

func (m *FwRule) GetUUID() string {
	if m != nil {
		return m.UUID
	}
	return ""
}

func (m *FwRule) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *FwRule) GetPosition() uint64 {
	if m != nil {
		return m.Position
	}
	return 0
}

func (m *FwRule) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *FwRule) GetParameters() string {
	if m != nil {
		return m.Parameters
	}
	return ""
}

func (m *FwRule) GetExpressions() []*Expressions {
	if m != nil {
		return m.Expressions
	}
	return nil
}

func (m *FwRule) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *FwRule) GetTargetParameters() string {
	if m != nil {
		return m.TargetParameters
	}
	return ""
}

type FwChain struct {
	Name                 string    `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Table                string    `protobuf:"bytes,2,opt,name=Table,proto3" json:"Table,omitempty"`
	Family               string    `protobuf:"bytes,3,opt,name=Family,proto3" json:"Family,omitempty"`
	Priority             string    `protobuf:"bytes,4,opt,name=Priority,proto3" json:"Priority,omitempty"`
	Type                 string    `protobuf:"bytes,5,opt,name=Type,proto3" json:"Type,omitempty"`
	Hook                 string    `protobuf:"bytes,6,opt,name=Hook,proto3" json:"Hook,omitempty"`
	Policy               string    `protobuf:"bytes,7,opt,name=Policy,proto3" json:"Policy,omitempty"`
	Rules                []*FwRule `protobuf:"bytes,8,rep,name=Rules,proto3" json:"Rules,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *FwChain) Reset()         { *m = FwChain{} }
func (m *FwChain) String() string { return proto.CompactTextString(m) }
func (*FwChain) ProtoMessage()    {}
func (*FwChain) Descriptor() ([]byte, []int) {
	return fileDescriptor_63867a62624c1283, []int{15}
}

func (m *FwChain) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FwChain.Unmarshal(m, b)
}
func (m *FwChain) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FwChain.Marshal(b, m, deterministic)
}
func (m *FwChain) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FwChain.Merge(m, src)
}
func (m *FwChain) XXX_Size() int {
	return xxx_messageInfo_FwChain.Size(m)
}
func (m *FwChain) XXX_DiscardUnknown() {
	xxx_messageInfo_FwChain.DiscardUnknown(m)
}

var xxx_messageInfo_FwChain proto.InternalMessageInfo

func (m *FwChain) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FwChain) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

func (m *FwChain) GetFamily() string {
	if m != nil {
		return m.Family
	}
	return ""
}

func (m *FwChain) GetPriority() string {
	if m != nil {
		return m.Priority
	}
	return ""
}

func (m *FwChain) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *FwChain) GetHook() string {
	if m != nil {
		return m.Hook
	}
	return ""
}

func (m *FwChain) GetPolicy() string {
	if m != nil {
		return m.Policy
	}
	return ""
}

func (m *FwChain) GetRules() []*FwRule {
	if m != nil {
		return m.Rules
	}
	return nil
}

type FwChains struct {
	// DEPRECATED: backward compatibility with iptables
	Rule                 *FwRule    `protobuf:"bytes,1,opt,name=Rule,proto3" json:"Rule,omitempty"`
	Chains               []*FwChain `protobuf:"bytes,2,rep,name=Chains,proto3" json:"Chains,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *FwChains) Reset()         { *m = FwChains{} }
func (m *FwChains) String() string { return proto.CompactTextString(m) }
func (*FwChains) ProtoMessage()    {}
func (*FwChains) Descriptor() ([]byte, []int) {
	return fileDescriptor_63867a62624c1283, []int{16}
}

func (m *FwChains) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FwChains.Unmarshal(m, b)
}
func (m *FwChains) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FwChains.Marshal(b, m, deterministic)
}
func (m *FwChains) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FwChains.Merge(m, src)
}
func (m *FwChains) XXX_Size() int {
	return xxx_messageInfo_FwChains.Size(m)
}
func (m *FwChains) XXX_DiscardUnknown() {
	xxx_messageInfo_FwChains.DiscardUnknown(m)
}

var xxx_messageInfo_FwChains proto.InternalMessageInfo

func (m *FwChains) GetRule() *FwRule {
	if m != nil {
		return m.Rule
	}
	return nil
}

func (m *FwChains) GetChains() []*FwChain {
	if m != nil {
		return m.Chains
	}
	return nil
}

type SysFirewall struct {
	Enabled              bool        `protobuf:"varint,1,opt,name=Enabled,proto3" json:"Enabled,omitempty"`
	Version              uint32      `protobuf:"varint,2,opt,name=Version,proto3" json:"Version,omitempty"`
	SystemRules          []*FwChains `protobuf:"bytes,3,rep,name=SystemRules,proto3" json:"SystemRules,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SysFirewall) Reset()         { *m = SysFirewall{} }
func (m *SysFirewall) String() string { return proto.CompactTextString(m) }
func (*SysFirewall) ProtoMessage()    {}
func (*SysFirewall) Descriptor() ([]byte, []int) {
	return fileDescriptor_63867a62624c1283, []int{17}
}

func (m *SysFirewall) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SysFirewall.Unmarshal(m, b)
}
func (m *SysFirewall) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SysFirewall.Marshal(b, m, deterministic)
}
func (m *SysFirewall) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SysFirewall.Merge(m, src)
}
func (m *SysFirewall) XXX_Size() int {
	return xxx_messageInfo_SysFirewall.Size(m)
}
func (m *SysFirewall) XXX_DiscardUnknown() {
	xxx_messageInfo_SysFirewall.DiscardUnknown(m)
}

var xxx_messageInfo_SysFirewall proto.InternalMessageInfo

func (m *SysFirewall) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *SysFirewall) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *SysFirewall) GetSystemRules() []*FwChains {
	if m != nil {
		return m.SystemRules
	}
	return nil
}

// client configuration sent on Subscribe()
type ClientConfig struct {
	Id                uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name              string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version           string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	IsFirewallRunning bool   `protobuf:"varint,4,opt,name=isFirewallRunning,proto3" json:"isFirewallRunning,omitempty"`
	// daemon configuration as json string
	Config               string       `protobuf:"bytes,5,opt,name=config,proto3" json:"config,omitempty"`
	LogLevel             uint32       `protobuf:"varint,6,opt,name=logLevel,proto3" json:"logLevel,omitempty"`
	Rules                []*Rule      `protobuf:"bytes,7,rep,name=rules,proto3" json:"rules,omitempty"`
	SystemFirewall       *SysFirewall `protobuf:"bytes,8,opt,name=systemFirewall,proto3" json:"systemFirewall,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ClientConfig) Reset()         { *m = ClientConfig{} }
func (m *ClientConfig) String() string { return proto.CompactTextString(m) }
func (*ClientConfig) ProtoMessage()    {}
func (*ClientConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_63867a62624c1283, []int{18}
}

func (m *ClientConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientConfig.Unmarshal(m, b)
}
func (m *ClientConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientConfig.Marshal(b, m, deterministic)
}
func (m *ClientConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientConfig.Merge(m, src)
}
func (m *ClientConfig) XXX_Size() int {
	return xxx_messageInfo_ClientConfig.Size(m)
}
func (m *ClientConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ClientConfig proto.InternalMessageInfo

func (m *ClientConfig) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ClientConfig) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ClientConfig) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *ClientConfig) GetIsFirewallRunning() bool {
	if m != nil {
		return m.IsFirewallRunning
	}
	return false
}

func (m *ClientConfig) GetConfig() string {
	if m != nil {
		return m.Config
	}
	return ""
}

func (m *ClientConfig) GetLogLevel() uint32 {
	if m != nil {
		return m.LogLevel
	}
	return 0
}

func (m *ClientConfig) GetRules() []*Rule {
	if m != nil {
		return m.Rules
	}
	return nil
}

func (m *ClientConfig) GetSystemFirewall() *SysFirewall {
	if m != nil {
		return m.SystemFirewall
	}
	return nil
}

// Notification message is sent to the clients (daemons) from the GUI (server)
// for several purposes:
//   - Start tasks.
//   - Change configurations (rules, firewall, configuration)
//   - Start / Stop interception or firewall.
//   - Sent back the status of each task (errors, ok)
//
// Notifications are sent via an always open streaming channel.
// It's also used indirectly to maintain the connection status with the GUI (server).
type Notification struct {
	Id         uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ClientName string `protobuf:"bytes,2,opt,name=clientName,proto3" json:"clientName,omitempty"`
	ServerName string `protobuf:"bytes,3,opt,name=serverName,proto3" json:"serverName,omitempty"`
	// CHANGE_CONFIG: 2, data: {"default_timeout": 1, ...}
	Type                 Action       `protobuf:"varint,4,opt,name=type,proto3,enum=protocol.Action" json:"type,omitempty"`
	Data                 string       `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	Rules                []*Rule      `protobuf:"bytes,6,rep,name=rules,proto3" json:"rules,omitempty"`
	SysFirewall          *SysFirewall `protobuf:"bytes,7,opt,name=sysFirewall,proto3" json:"sysFirewall,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Notification) Reset()         { *m = Notification{} }
func (m *Notification) String() string { return proto.CompactTextString(m) }
func (*Notification) ProtoMessage()    {}
func (*Notification) Descriptor() ([]byte, []int) {
	return fileDescriptor_63867a62624c1283, []int{19}
}

func (m *Notification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Notification.Unmarshal(m, b)
}
func (m *Notification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Notification.Marshal(b, m, deterministic)
}
func (m *Notification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Notification.Merge(m, src)
}
func (m *Notification) XXX_Size() int {
	return xxx_messageInfo_Notification.Size(m)
}
func (m *Notification) XXX_DiscardUnknown() {
	xxx_messageInfo_Notification.DiscardUnknown(m)
}

var xxx_messageInfo_Notification proto.InternalMessageInfo

func (m *Notification) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Notification) GetClientName() string {
	if m != nil {
		return m.ClientName
	}
	return ""
}

func (m *Notification) GetServerName() string {
	if m != nil {
		return m.ServerName
	}
	return ""
}

func (m *Notification) GetType() Action {
	if m != nil {
		return m.Type
	}
	return Action_NONE
}

func (m *Notification) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *Notification) GetRules() []*Rule {
	if m != nil {
		return m.Rules
	}
	return nil
}

func (m *Notification) GetSysFirewall() *SysFirewall {
	if m != nil {
		return m.SysFirewall
	}
	return nil
}

// notification reply sent to the server (GUI)
type NotificationReply struct {
	Id                   uint64                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Code                 NotificationReplyCode `protobuf:"varint,2,opt,name=code,proto3,enum=protocol.NotificationReplyCode" json:"code,omitempty"`
	Data                 string                `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *NotificationReply) Reset()         { *m = NotificationReply{} }
func (m *NotificationReply) String() string { return proto.CompactTextString(m) }
func (*NotificationReply) ProtoMessage()    {}
func (*NotificationReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_63867a62624c1283, []int{20}
}

func (m *NotificationReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotificationReply.Unmarshal(m, b)
}
func (m *NotificationReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotificationReply.Marshal(b, m, deterministic)
}
func (m *NotificationReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotificationReply.Merge(m, src)
}
func (m *NotificationReply) XXX_Size() int {
	return xxx_messageInfo_NotificationReply.Size(m)
}
func (m *NotificationReply) XXX_DiscardUnknown() {
	xxx_messageInfo_NotificationReply.DiscardUnknown(m)
}

var xxx_messageInfo_NotificationReply proto.InternalMessageInfo

func (m *NotificationReply) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *NotificationReply) GetCode() NotificationReplyCode {
	if m != nil {
		return m.Code
	}
	return NotificationReplyCode_OK
}

func (m *NotificationReply) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func init() {
	proto.RegisterEnum("protocol.Action", Action_name, Action_value)
	proto.RegisterEnum("protocol.NotificationReplyCode", NotificationReplyCode_name, NotificationReplyCode_value)
	proto.RegisterEnum("protocol.Alert_Priority", Alert_Priority_name, Alert_Priority_value)
	proto.RegisterEnum("protocol.Alert_Type", Alert_Type_name, Alert_Type_value)
	proto.RegisterEnum("protocol.Alert_Action", Alert_Action_name, Alert_Action_value)
	proto.RegisterEnum("protocol.Alert_What", Alert_What_name, Alert_What_value)
	proto.RegisterType((*Alert)(nil), "protocol.Alert")
	proto.RegisterType((*MsgResponse)(nil), "protocol.MsgResponse")
	proto.RegisterType((*Event)(nil), "protocol.Event")
	proto.RegisterType((*Statistics)(nil), "protocol.Statistics")
	proto.RegisterMapType((map[string]uint64)(nil), "protocol.Statistics.ByAddressEntry")
	proto.RegisterMapType((map[string]uint64)(nil), "protocol.Statistics.ByExecutableEntry")
	proto.RegisterMapType((map[string]uint64)(nil), "protocol.Statistics.ByHostEntry")
	proto.RegisterMapType((map[string]uint64)(nil), "protocol.Statistics.ByPortEntry")
	proto.RegisterMapType((map[string]uint64)(nil), "protocol.Statistics.ByProtoEntry")
	proto.RegisterMapType((map[string]uint64)(nil), "protocol.Statistics.ByUidEntry")
	proto.RegisterType((*PingRequest)(nil), "protocol.PingRequest")
	proto.RegisterType((*PingReply)(nil), "protocol.PingReply")
	proto.RegisterType((*StringInt)(nil), "protocol.StringInt")
	proto.RegisterType((*Process)(nil), "protocol.Process")
	proto.RegisterMapType((map[string]string)(nil), "protocol.Process.ChecksumsEntry")
	proto.RegisterMapType((map[string]string)(nil), "protocol.Process.EnvEntry")
	proto.RegisterType((*Connection)(nil), "protocol.Connection")
	proto.RegisterMapType((map[string]string)(nil), "protocol.Connection.ProcessChecksumsEntry")
	proto.RegisterMapType((map[string]string)(nil), "protocol.Connection.ProcessEnvEntry")
	proto.RegisterType((*Operator)(nil), "protocol.Operator")
	proto.RegisterType((*Rule)(nil), "protocol.Rule")
	proto.RegisterType((*StatementValues)(nil), "protocol.StatementValues")
	proto.RegisterType((*Statement)(nil), "protocol.Statement")
	proto.RegisterType((*Expressions)(nil), "protocol.Expressions")
	proto.RegisterType((*FwRule)(nil), "protocol.FwRule")
	proto.RegisterType((*FwChain)(nil), "protocol.FwChain")
	proto.RegisterType((*FwChains)(nil), "protocol.FwChains")
	proto.RegisterType((*SysFirewall)(nil), "protocol.SysFirewall")
	proto.RegisterType((*ClientConfig)(nil), "protocol.ClientConfig")
	proto.RegisterType((*Notification)(nil), "protocol.Notification")
	proto.RegisterType((*NotificationReply)(nil), "protocol.NotificationReply")
}

func init() {
	proto.RegisterFile("ui.proto", fileDescriptor_63867a62624c1283)
}

var fileDescriptor_63867a62624c1283 = []byte{
	// 2442 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x58, 0xcd, 0x72, 0xe3, 0xc6,
	0xf1, 0x17, 0x49, 0x10, 0x24, 0x9b, 0xfa, 0x80, 0x66, 0x3f, 0x0c, 0xcb, 0x7f, 0xdb, 0x32, 0xbc,
	0x7f, 0x5b, 0x56, 0xb9, 0xb4, 0xf1, 0xee, 0xfa, 0xb3, 0xec, 0x24, 0x5c, 0x0a, 0x5a, 0x31, 0xe2,
	0x92, 0xac, 0x11, 0xb5, 0xaa, 0x4a, 0x0e, 0x2c, 0x10, 0x98, 0x95, 0x50, 0x4b, 0x01, 0x0c, 0x06,
	0x94, 0x96, 0xaf, 0x90, 0xaa, 0x1c, 0x92, 0x54, 0xce, 0xa9, 0xca, 0x0b, 0xe4, 0x09, 0x72, 0xce,
	0x31, 0x8f, 0x93, 0x6b, 0xaa, 0x7b, 0x06, 0x24, 0x44, 0x4a, 0xeb, 0x52, 0x4e, 0x98, 0xee, 0xfe,
	0x75, 0xcf, 0x4c, 0x77, 0xa3, 0x7b, 0x66, 0xa0, 0x3a, 0x09, 0xf7, 0xc6, 0x49, 0x9c, 0xc6, 0xac,
	0x4a, 0x1f, 0x3f, 0x1e, 0x39, 0x7f, 0x2c, 0x43, 0xb9, 0x31, 0x12, 0x49, 0xca, 0xd6, 0xa1, 0x18,
	0x06, 0x76, 0x61, 0xbb, 0xb0, 0x63, 0xf0, 0x62, 0x18, 0xb0, 0x1d, 0x30, 0xd2, 0xe9, 0x58, 0xd8,
	0xc5, 0xed, 0xc2, 0xce, 0xfa, 0x93, 0xfb, 0x7b, 0x99, 0xca, 0x1e, 0xc1, 0xf7, 0xfa, 0xd3, 0xb1,
	0xe0, 0x84, 0x60, 0x7b, 0x60, 0x7a, 0x7e, 0x1a, 0xc6, 0x91, 0x5d, 0x22, 0xec, 0xc3, 0x45, 0x6c,
	0x83, 0xa4, 0x5c, 0xa3, 0xd8, 0x33, 0xa8, 0x8e, 0x93, 0x30, 0x4e, 0xc2, 0x74, 0x6a, 0x1b, 0xa4,
	0x61, 0x2f, 0x6a, 0xf4, 0xb4, 0x9c, 0xcf, 0x90, 0xb8, 0x9e, 0xab, 0x73, 0x2f, 0xb5, 0xcb, 0x37,
	0xaf, 0xe7, 0xf4, 0xdc, 0x4b, 0x39, 0x21, 0xd8, 0x7d, 0x30, 0x52, 0xf1, 0x36, 0xb5, 0xcd, 0xed,
	0xc2, 0x4e, 0xed, 0x70, 0x85, 0x13, 0xc5, 0x3e, 0x07, 0x63, 0x9c, 0xc4, 0xbe, 0x5d, 0xdd, 0x2e,
	0xec, 0xd4, 0x9f, 0x6c, 0xce, 0xf5, 0x7b, 0x49, 0xec, 0x0b, 0x29, 0x11, 0x88, 0x00, 0xb6, 0x0b,
	0x86, 0x1f, 0x47, 0x91, 0x5d, 0x23, 0x60, 0x6e, 0xa2, 0x66, 0x1c, 0x45, 0x82, 0xb6, 0x80, 0x58,
	0xc4, 0xb0, 0x47, 0x60, 0x24, 0x93, 0x91, 0xb0, 0x81, 0xb0, 0xeb, 0x73, 0x2c, 0x9f, 0x8c, 0x04,
	0xa2, 0x50, 0xca, 0x76, 0xc1, 0x7c, 0x7d, 0x45, 0xb8, 0x3a, 0xe1, 0xac, 0x39, 0xee, 0xe0, 0x4a,
	0x23, 0x35, 0xc2, 0xf9, 0x02, 0xaa, 0xd9, 0xe6, 0x59, 0x05, 0x4a, 0xed, 0xee, 0xa9, 0xb5, 0xc2,
	0x00, 0xcc, 0x97, 0xee, 0x7e, 0xeb, 0xe4, 0xa5, 0x55, 0x60, 0x55, 0x30, 0x0e, 0x5b, 0x2f, 0x0e,
	0xad, 0xa2, 0xb3, 0x03, 0x06, 0x46, 0x81, 0xd5, 0xa0, 0xec, 0x72, 0xde, 0xe5, 0xd6, 0x0a, 0xab,
	0x43, 0xe5, 0xb4, 0xc1, 0x3b, 0xad, 0xce, 0x0b, 0x85, 0x6c, 0x75, 0x0e, 0xba, 0x56, 0xd1, 0x79,
	0x02, 0xa6, 0x8a, 0x01, 0xf2, 0x3a, 0xdd, 0x8e, 0x6b, 0xad, 0xb0, 0x75, 0x80, 0xe3, 0xc3, 0xee,
	0xe9, 0xa0, 0xd1, 0x76, 0x79, 0xdf, 0x2a, 0x10, 0xdd, 0x78, 0xe5, 0x0e, 0xfa, 0xdd, 0xc1, 0xfe,
	0x73, 0xab, 0xe8, 0x8c, 0xc0, 0x40, 0x9f, 0xa2, 0xc9, 0x17, 0x6e, 0xc7, 0xe5, 0xad, 0xa6, 0xb5,
	0xc2, 0x2c, 0x58, 0xed, 0xf1, 0x6e, 0x73, 0xf0, 0xb2, 0xdb, 0x69, 0xf5, 0xbb, 0xdc, 0x2a, 0xb0,
	0x55, 0xa8, 0x1e, 0xb4, 0xb8, 0x7b, 0xda, 0x68, 0xb7, 0xad, 0x22, 0x1a, 0x69, 0x76, 0x3b, 0x1d,
	0xb7, 0xd9, 0x6f, 0x75, 0x3b, 0x56, 0x09, 0xa7, 0xe3, 0x27, 0x6d, 0xd7, 0x32, 0xd0, 0x4c, 0xc7,
	0xed, 0xb7, 0x5b, 0x9d, 0x23, 0xab, 0x8c, 0x66, 0x8e, 0x5c, 0xde, 0x71, 0xdb, 0x03, 0xf7, 0x95,
	0xdb, 0xe9, 0x5b, 0xe6, 0x73, 0x13, 0x8c, 0xc0, 0x4b, 0x3d, 0xe7, 0x43, 0xa8, 0xbf, 0x94, 0x67,
	0x5c, 0xc8, 0x71, 0x1c, 0x49, 0xb1, 0x98, 0x94, 0xce, 0x9f, 0x0a, 0x50, 0x76, 0x2f, 0x45, 0x94,
	0x32, 0x06, 0x46, 0x1a, 0x5e, 0x08, 0x92, 0xd5, 0x38, 0x8d, 0xd9, 0x33, 0x00, 0x7f, 0x16, 0x23,
	0x4a, 0xdc, 0x5b, 0xe2, 0xc7, 0x73, 0x38, 0xe6, 0xe8, 0x18, 0x96, 0x6e, 0x8a, 0xa1, 0x8e, 0xe0,
	0x16, 0x54, 0x27, 0x51, 0xf8, 0x36, 0xf2, 0xa2, 0x98, 0x52, 0xb6, 0xc4, 0x67, 0xb4, 0xf3, 0xaf,
	0x2a, 0xc0, 0x71, 0xea, 0xa5, 0xa1, 0x4c, 0x43, 0x5f, 0xb2, 0xff, 0x87, 0xf5, 0xc0, 0x13, 0x17,
	0x71, 0x34, 0xb8, 0x14, 0x89, 0xc4, 0x85, 0xa8, 0x25, 0xae, 0x29, 0xee, 0x2b, 0xc5, 0x64, 0xf7,
	0xa1, 0x8c, 0x96, 0x25, 0x2d, 0xd3, 0xe0, 0x8a, 0x60, 0x0f, 0xc1, 0x9c, 0x8c, 0x69, 0x5f, 0x25,
	0x62, 0x6b, 0x8a, 0x7d, 0x0a, 0x6b, 0x41, 0x24, 0x07, 0x89, 0xf6, 0x8b, 0xa4, 0x45, 0x18, 0x7c,
	0x35, 0x88, 0x64, 0xe6, 0x2b, 0xc9, 0xb6, 0xa1, 0x3e, 0xdf, 0x96, 0xa4, 0x1f, 0xc5, 0xe0, 0x79,
	0x16, 0xb3, 0xa1, 0x12, 0x9e, 0x45, 0x71, 0x22, 0x02, 0xfa, 0x39, 0x0c, 0x9e, 0x91, 0xb8, 0x41,
	0xcf, 0xf7, 0xc5, 0x38, 0x15, 0x81, 0x5d, 0x21, 0xd1, 0x8c, 0x46, 0xad, 0x20, 0x89, 0xc7, 0x63,
	0x11, 0xd0, 0xcf, 0x63, 0xf0, 0x8c, 0x64, 0x1f, 0x40, 0x0d, 0xd7, 0x3d, 0x38, 0x0f, 0x53, 0x49,
	0xff, 0x8b, 0xc1, 0xab, 0xc8, 0x38, 0x0c, 0x53, 0xc9, 0x3e, 0x86, 0x3a, 0x09, 0x2f, 0x42, 0x89,
	0x2b, 0x06, 0x12, 0x03, 0xb2, 0x5e, 0x12, 0x87, 0xfd, 0x08, 0xd5, 0xe1, 0x74, 0x40, 0xee, 0xb6,
	0xeb, 0xdb, 0xa5, 0x9d, 0xfa, 0x93, 0x4f, 0xe6, 0xce, 0x9f, 0x7b, 0x74, 0xef, 0xf9, 0xb4, 0x87,
	0x5c, 0x37, 0x4a, 0x93, 0x29, 0xaf, 0x0c, 0x15, 0xc5, 0x9e, 0x03, 0x0c, 0xa7, 0x03, 0x2f, 0x08,
	0x12, 0x21, 0xa5, 0xbd, 0x4a, 0xfa, 0x9f, 0xde, 0xa2, 0xdf, 0x50, 0x28, 0x65, 0xa1, 0x36, 0xcc,
	0x68, 0xf6, 0x3d, 0x54, 0x86, 0xd3, 0xc1, 0x79, 0x2c, 0x53, 0x7b, 0x8d, 0x0c, 0x6c, 0xdf, 0x62,
	0xe0, 0x30, 0x96, 0xa9, 0xd2, 0x36, 0x87, 0x44, 0x68, 0xd5, 0x71, 0x9c, 0xa4, 0xf6, 0xfa, 0x3b,
	0x55, 0x7b, 0x71, 0x32, 0x57, 0x45, 0x82, 0x7d, 0x03, 0xe6, 0x70, 0x3a, 0x98, 0x84, 0x81, 0xbd,
	0x41, 0x9a, 0x1f, 0xdf, 0xa2, 0x79, 0x12, 0x06, 0x4a, 0xb1, 0x3c, 0xc4, 0x31, 0x3b, 0x82, 0xb5,
	0xe1, 0x74, 0x20, 0xde, 0x0a, 0x7f, 0x92, 0x7a, 0xc3, 0x91, 0xb0, 0x2d, 0x52, 0xff, 0xec, 0x16,
	0x75, 0x77, 0x06, 0x54, 0x56, 0x56, 0x87, 0x39, 0x16, 0xfb, 0x1c, 0x4c, 0x81, 0x3f, 0x92, 0xb4,
	0x37, 0xc9, 0xca, 0xc6, 0xdc, 0x0a, 0xfd, 0x60, 0x5c, 0x8b, 0xb7, 0x7e, 0x80, 0xd5, 0x7c, 0x00,
	0x98, 0x05, 0xa5, 0x37, 0x62, 0xaa, 0x93, 0x1a, 0x87, 0x98, 0xca, 0x97, 0xde, 0x68, 0x22, 0xb2,
	0x54, 0x26, 0xe2, 0x87, 0xe2, 0x77, 0x85, 0xad, 0x1f, 0x61, 0xfd, 0xba, 0xf3, 0xef, 0xa4, 0xfd,
	0x3d, 0xd4, 0x73, 0x9e, 0xbf, 0xbb, 0xea, 0xcc, 0xf3, 0x77, 0x52, 0xfd, 0x0e, 0x60, 0xee, 0xfa,
	0x3b, 0x69, 0xfe, 0x0a, 0x36, 0x97, 0xbc, 0x7e, 0x17, 0x03, 0x4e, 0x0b, 0xea, 0xbd, 0x30, 0x3a,
	0xe3, 0xe2, 0xf7, 0x13, 0x21, 0x97, 0x3b, 0xf2, 0x2e, 0x94, 0x65, 0xea, 0xa5, 0x72, 0xb9, 0xb2,
	0xcd, 0xe3, 0xce, 0x15, 0xc4, 0xf9, 0x00, 0x6a, 0xca, 0xd4, 0x78, 0x34, 0x5d, 0xaa, 0xa2, 0x4f,
	0xa1, 0x76, 0x9c, 0x26, 0x61, 0x74, 0xd6, 0x8a, 0xd2, 0x9f, 0x5b, 0xe0, 0x9a, 0x5e, 0xa0, 0xf3,
	0x37, 0x03, 0x2a, 0xba, 0x55, 0xa2, 0xce, 0x78, 0x66, 0x11, 0x87, 0x58, 0x8e, 0xc7, 0xc8, 0x52,
	0x7b, 0xa2, 0x31, 0xa2, 0x30, 0xc9, 0x55, 0x25, 0xc3, 0x21, 0xa2, 0xfc, 0xf8, 0xe2, 0x82, 0xaa,
	0x57, 0x8d, 0xd3, 0x98, 0x34, 0xbd, 0xf4, 0x9c, 0xca, 0x55, 0x8d, 0xd3, 0x18, 0x79, 0x5e, 0x72,
	0x26, 0x6d, 0x73, 0xbb, 0x84, 0x3c, 0x1c, 0xb3, 0x2f, 0xa1, 0x24, 0xa2, 0x4b, 0xbb, 0x42, 0xd9,
	0xba, 0xb5, 0xd4, 0xbe, 0xf7, 0xdc, 0xe8, 0x52, 0xe5, 0x39, 0xc2, 0x70, 0x6e, 0xff, 0x4a, 0xd5,
	0xab, 0x1a, 0xc7, 0x21, 0xfb, 0x25, 0xd4, 0xfc, 0x73, 0xe1, 0xbf, 0x91, 0x93, 0x0b, 0xac, 0x55,
	0x0b, 0xbf, 0x6c, 0x66, 0xa5, 0x99, 0x41, 0x74, 0xad, 0x98, 0xa9, 0xb0, 0xf7, 0xa1, 0x1a, 0xc6,
	0x83, 0x44, 0x78, 0x41, 0x56, 0xcb, 0x2a, 0x61, 0xcc, 0x91, 0xc4, 0x32, 0x18, 0xc6, 0x83, 0xab,
	0x24, 0x4c, 0x85, 0xa4, 0x16, 0x6f, 0xf0, 0x6a, 0x18, 0x9f, 0x12, 0x8d, 0xc2, 0x48, 0xa4, 0x5a,
	0x71, 0x55, 0x09, 0x23, 0x91, 0x2a, 0xcd, 0x0f, 0x01, 0x50, 0xa8, 0x55, 0xd7, 0x48, 0x8a, 0x70,
	0xad, 0xfb, 0x0d, 0xac, 0x8e, 0xd5, 0xc2, 0x06, 0x69, 0x22, 0x84, 0xae, 0x34, 0xf7, 0xf2, 0x81,
	0xd7, 0x61, 0xe4, 0x75, 0x0d, 0xec, 0x27, 0x42, 0x6c, 0x7d, 0x03, 0xd5, 0xcc, 0x1d, 0x3f, 0x17,
	0xdf, 0xda, 0xc2, 0xff, 0x7a, 0xdd, 0x01, 0x77, 0xd1, 0x76, 0xfe, 0x5e, 0x06, 0x98, 0xf7, 0x58,
	0x6c, 0x29, 0xd9, 0x3a, 0xb5, 0xfe, 0x8c, 0x66, 0x0f, 0xc0, 0x94, 0x89, 0x3f, 0x08, 0xc7, 0x99,
	0x15, 0x99, 0xf8, 0xad, 0x31, 0xfa, 0x18, 0xd9, 0x54, 0x55, 0x4b, 0x94, 0x7c, 0x15, 0x99, 0xf8,
	0x54, 0x34, 0x1f, 0x80, 0x19, 0xc8, 0x14, 0x35, 0x54, 0xf2, 0x94, 0x03, 0x99, 0x2a, 0x0d, 0x64,
	0x53, 0x09, 0x57, 0x19, 0x54, 0x09, 0x64, 0x4a, 0x15, 0x5a, 0x8b, 0xc8, 0x98, 0xa9, 0x8c, 0x05,
	0x32, 0x25, 0x63, 0xef, 0x41, 0x65, 0x22, 0x45, 0x32, 0x08, 0x55, 0xb3, 0x5b, 0xe3, 0x26, 0x92,
	0xad, 0x00, 0xe3, 0x91, 0x39, 0x3c, 0x54, 0xd9, 0xb3, 0xc6, 0x6b, 0x9a, 0xd3, 0x0a, 0xd8, 0x27,
	0xf3, 0x78, 0x50, 0xce, 0xd6, 0x68, 0xc6, 0xcc, 0xf5, 0x3d, 0x4c, 0xdd, 0x8f, 0x21, 0x23, 0x07,
	0x98, 0x80, 0x40, 0x88, 0xcc, 0x68, 0xf3, 0xea, 0x9a, 0x0d, 0xca, 0xf1, 0x3a, 0xe5, 0x78, 0xa6,
	0xd4, 0xc0, 0x54, 0x77, 0xe7, 0x36, 0x30, 0xe5, 0x55, 0x6f, 0x7b, 0x74, 0xd3, 0x41, 0x26, 0xcb,
	0xdb, 0x59, 0xf2, 0x67, 0x33, 0xb9, 0xd1, 0x25, 0x3b, 0x85, 0xcd, 0xd9, 0x52, 0x66, 0x99, 0xaf,
	0xfa, 0xdc, 0xee, 0xbb, 0x8c, 0x2d, 0xfc, 0x03, 0xd6, 0x78, 0x81, 0xfd, 0x3f, 0xa7, 0xe5, 0x4f,
	0xb0, 0xb1, 0xb0, 0xde, 0x3b, 0x65, 0x67, 0x13, 0x1e, 0xdc, 0xb8, 0xc2, 0x3b, 0x25, 0xe9, 0x9f,
	0x0b, 0x50, 0xed, 0x8e, 0x45, 0xe2, 0xa5, 0x71, 0x42, 0x87, 0x48, 0xbc, 0xe3, 0x64, 0x87, 0x48,
	0x3c, 0x4d, 0xdb, 0x50, 0x89, 0x51, 0x1e, 0x05, 0x5a, 0x39, 0x23, 0x11, 0x8d, 0x67, 0x54, 0xca,
	0xcc, 0x1a, 0xa7, 0x31, 0xfb, 0x3f, 0xa8, 0x49, 0x11, 0xc9, 0x30, 0x0d, 0x2f, 0x05, 0x65, 0x66,
	0x95, 0xcf, 0x19, 0xec, 0x33, 0x30, 0x46, 0x21, 0x65, 0x26, 0x3a, 0x88, 0xcd, 0x1d, 0x94, 0xad,
	0x80, 0x93, 0xdc, 0xf9, 0x43, 0x11, 0x0c, 0x3c, 0x6d, 0xe2, 0xe4, 0x7e, 0x22, 0x3c, 0x3c, 0x85,
	0x15, 0xe8, 0x98, 0x99, 0x91, 0x38, 0x79, 0xe4, 0x5d, 0x64, 0x1b, 0xa2, 0x31, 0x1e, 0xf8, 0x02,
	0x21, 0xfd, 0x24, 0x1c, 0xcf, 0x6e, 0x5f, 0x35, 0x9e, 0x67, 0xa1, 0x3d, 0x11, 0x61, 0x33, 0x0a,
	0xf4, 0xe2, 0x32, 0x92, 0x7d, 0x84, 0x99, 0x2e, 0x7c, 0x11, 0x88, 0xc8, 0x17, 0xf4, 0xeb, 0x54,
	0x79, 0x8e, 0x83, 0x1e, 0x8c, 0xe2, 0x51, 0x7c, 0x46, 0xbf, 0x4e, 0x95, 0x2b, 0x02, 0xcf, 0xa7,
	0xfa, 0xaa, 0x57, 0xa1, 0xc9, 0xb2, 0x2b, 0xdd, 0x16, 0x54, 0x83, 0x49, 0xe2, 0x91, 0x44, 0xd5,
	0xdc, 0x19, 0xcd, 0xf6, 0xa0, 0x1a, 0xeb, 0xed, 0xea, 0x3b, 0xd5, 0x4d, 0x8e, 0x98, 0x61, 0x9c,
	0xef, 0x61, 0x03, 0xfb, 0x99, 0xb8, 0x10, 0x51, 0xfa, 0x0a, 0xe3, 0x46, 0xfd, 0xe6, 0x68, 0x1e,
	0xe0, 0x23, 0x15, 0xe0, 0x57, 0xf9, 0x00, 0x13, 0xe1, 0x0c, 0xb1, 0xb1, 0x69, 0x55, 0xec, 0x7a,
	0xdd, 0xb1, 0xd6, 0x29, 0x76, 0xc7, 0xe8, 0xc1, 0x4e, 0xce, 0x83, 0x38, 0x66, 0x5f, 0x81, 0xa9,
	0xa6, 0xb0, 0x4b, 0x14, 0xa2, 0xf7, 0xaf, 0xf7, 0xd4, 0xdc, 0x1a, 0xb8, 0x06, 0x3a, 0xbf, 0x86,
	0xba, 0xfb, 0x76, 0x8c, 0x27, 0x1a, 0x3a, 0x52, 0x7f, 0x95, 0x9b, 0x92, 0x26, 0x5b, 0xf8, 0x11,
	0xb4, 0x88, 0xcf, 0x51, 0xce, 0x3f, 0x8b, 0x60, 0xaa, 0x7b, 0x1f, 0x6e, 0xa3, 0x4f, 0x47, 0x39,
	0xb5, 0x4c, 0x45, 0x20, 0xb7, 0x79, 0xee, 0x85, 0x51, 0xb6, 0x39, 0x22, 0x70, 0xfd, 0x27, 0x27,
	0xad, 0xfd, 0x2c, 0xfd, 0x70, 0x8c, 0xf1, 0x75, 0xaf, 0xc7, 0x57, 0x93, 0x18, 0x91, 0x5e, 0x8c,
	0x69, 0x18, 0x47, 0xfa, 0x26, 0x30, 0xa3, 0x31, 0x6f, 0xf6, 0x73, 0x79, 0x63, 0xaa, 0xbc, 0xc9,
	0xb1, 0x30, 0x3b, 0x7a, 0x5e, 0xe2, 0x5d, 0x88, 0x54, 0x24, 0x52, 0xc7, 0x3a, 0xc7, 0x61, 0xdf,
	0x5e, 0x73, 0x82, 0x5d, 0x25, 0xe7, 0x3d, 0xc8, 0x1d, 0x21, 0xe7, 0x42, 0x7e, 0xcd, 0x5d, 0x0f,
	0xc1, 0xec, 0x7b, 0xc9, 0x99, 0x48, 0x75, 0xed, 0xd4, 0x14, 0xdb, 0x05, 0x4b, 0x8d, 0x72, 0xd3,
	0xaa, 0xda, 0xb9, 0xc4, 0x77, 0xfe, 0x5d, 0x80, 0xca, 0xc1, 0xd5, 0xcc, 0x29, 0x14, 0xd4, 0x42,
	0x2e, 0xa8, 0x33, 0xa7, 0x16, 0xf3, 0x4e, 0x7d, 0x08, 0xe6, 0x81, 0x77, 0x11, 0x8e, 0xa6, 0xda,
	0x81, 0x9a, 0x22, 0x47, 0xe5, 0x5f, 0x23, 0x6a, 0x7c, 0x7e, 0x01, 0x67, 0xea, 0x86, 0x9d, 0x9d,
	0x4d, 0xe8, 0xb6, 0xcd, 0xc0, 0x38, 0x8c, 0xe3, 0x37, 0xda, 0x6b, 0x34, 0x46, 0xdb, 0xbd, 0x78,
	0x14, 0xfa, 0xd3, 0xec, 0xb7, 0x50, 0x14, 0xfb, 0x0c, 0xca, 0x9c, 0x2e, 0x79, 0xca, 0x41, 0x4b,
	0xf7, 0x7e, 0xae, 0xc4, 0xce, 0xef, 0xa0, 0xaa, 0x37, 0x24, 0xd9, 0x23, 0x55, 0x0a, 0x74, 0x2e,
	0x2d, 0xab, 0xa8, 0x42, 0xf1, 0x05, 0x98, 0x0a, 0x6f, 0x17, 0xc9, 0xf4, 0x66, 0x1e, 0x47, 0x12,
	0xae, 0x01, 0xce, 0x15, 0xd4, 0x8f, 0xa7, 0xf2, 0x20, 0x4c, 0xc4, 0x95, 0x37, 0x1a, 0xe5, 0x53,
	0xa6, 0x70, 0x3d, 0x65, 0x6c, 0xa8, 0xe8, 0xdb, 0xa9, 0x3e, 0xf9, 0x65, 0x24, 0x7b, 0x46, 0x26,
	0x52, 0x71, 0xa1, 0x76, 0x53, 0x5a, 0x2c, 0x67, 0xd9, 0xe2, 0x79, 0x1e, 0xe6, 0xfc, 0xa5, 0x08,
	0xab, 0xcd, 0x51, 0x28, 0xa2, 0xb4, 0x19, 0x47, 0xaf, 0xc3, 0xb3, 0xa5, 0x03, 0xed, 0x4d, 0x35,
	0xcd, 0x86, 0x4a, 0x76, 0x6f, 0x56, 0x71, 0xca, 0x48, 0xf6, 0x25, 0x6c, 0x86, 0xb3, 0x6d, 0xf0,
	0x49, 0x14, 0x85, 0xd1, 0x99, 0xce, 0xfa, 0x65, 0x01, 0x86, 0xc4, 0xa7, 0x59, 0x75, 0xf0, 0x34,
	0x85, 0xe1, 0x1e, 0xc5, 0x67, 0x6d, 0x71, 0x29, 0x46, 0xfa, 0x54, 0x30, 0xa3, 0xd9, 0xa3, 0xec,
	0x4e, 0xae, 0x0e, 0x99, 0x8b, 0x4f, 0x01, 0xfa, 0x8e, 0xfe, 0x13, 0xac, 0x4b, 0xda, 0x65, 0x36,
	0xa5, 0x7e, 0x52, 0xca, 0xa5, 0x7f, 0xce, 0xdf, 0x7c, 0x01, 0xec, 0xfc, 0xa7, 0x00, 0xab, 0x9d,
	0x38, 0x0d, 0x5f, 0x87, 0xbe, 0xaa, 0x8f, 0x8b, 0x5e, 0xf9, 0x08, 0xc0, 0x27, 0xaf, 0xe5, 0xaa,
	0x55, 0x8e, 0x83, 0x72, 0x29, 0x92, 0x4b, 0x91, 0x90, 0x5c, 0x39, 0x29, 0xc7, 0xc1, 0x04, 0xa2,
	0xa6, 0xa6, 0x9e, 0xd6, 0x72, 0x09, 0xa4, 0x9f, 0xe1, 0x54, 0x9b, 0xcb, 0x9a, 0x59, 0x39, 0xd7,
	0xcc, 0x66, 0xfb, 0x37, 0xdf, 0xb5, 0xff, 0x6f, 0xa1, 0x2e, 0xe7, 0xfb, 0xa3, 0x8c, 0xbf, 0x75,
	0xf3, 0x79, 0xa4, 0x33, 0x82, 0xcd, 0xfc, 0xc6, 0x6f, 0xbc, 0x9b, 0xb0, 0xa7, 0x78, 0x45, 0x08,
	0xb2, 0x67, 0xc7, 0xdc, 0xd5, 0x78, 0x49, 0xb5, 0x19, 0x07, 0x82, 0x13, 0xf8, 0xa6, 0xce, 0xbc,
	0xfb, 0xd7, 0xe2, 0x0d, 0x8f, 0x5e, 0xef, 0xc1, 0x3d, 0xb7, 0xd3, 0x78, 0xde, 0x76, 0x07, 0xad,
	0x4e, 0xdf, 0xe5, 0x4d, 0xb7, 0x47, 0x0f, 0x55, 0x05, 0x66, 0xc3, 0xfd, 0xfd, 0xd6, 0xf1, 0xb2,
	0xa4, 0xc8, 0xee, 0xc1, 0x86, 0x56, 0x99, 0xbd, 0x73, 0x95, 0xd8, 0x7d, 0xb0, 0x32, 0xf8, 0x8c,
	0x6b, 0x20, 0x94, 0xbb, 0xed, 0x6e, 0x63, 0x7f, 0x70, 0x70, 0x3a, 0xe0, 0x27, 0x6d, 0xf7, 0xd8,
	0x2a, 0xb3, 0x4d, 0x58, 0x6b, 0x1e, 0x36, 0x3a, 0x2f, 0xdc, 0x41, 0xb3, 0xdb, 0x39, 0x68, 0xbd,
	0xb0, 0x4c, 0xb6, 0x01, 0x75, 0x6d, 0x92, 0x1e, 0xc7, 0x2a, 0xcc, 0x82, 0xd5, 0xcc, 0x1c, 0x71,
	0xaa, 0x08, 0xd9, 0x77, 0xdb, 0x6e, 0x5f, 0x33, 0x6a, 0xc8, 0xd0, 0x66, 0x88, 0x01, 0x6c, 0x0d,
	0x6a, 0xed, 0xee, 0x8b, 0x41, 0xdb, 0x7d, 0xe5, 0xb6, 0xad, 0x3a, 0xee, 0xf1, 0xb8, 0xdf, 0xed,
	0x59, 0xab, 0x6c, 0x1d, 0xa0, 0xdf, 0x38, 0x3e, 0x1a, 0x1c, 0xf7, 0x1b, 0xbc, 0x6f, 0xad, 0x21,
	0x50, 0xd3, 0xdd, 0x9e, 0xb5, 0xbe, 0xbb, 0x0b, 0x0f, 0x6e, 0x74, 0x25, 0x33, 0xa1, 0xd8, 0x3d,
	0xb2, 0x56, 0xe6, 0xcf, 0x89, 0x85, 0x27, 0xff, 0x28, 0x42, 0xf1, 0xa4, 0xc5, 0x9e, 0x81, 0x81,
	0x97, 0x49, 0x96, 0x0b, 0x72, 0xee, 0x9e, 0xba, 0x75, 0x6f, 0x91, 0x3d, 0x1e, 0x4d, 0x9d, 0x15,
	0xf6, 0x15, 0x54, 0x1a, 0xf2, 0x8d, 0x6a, 0x73, 0x37, 0x1d, 0x37, 0xb7, 0x16, 0xf2, 0xcb, 0x59,
	0x61, 0x3f, 0x41, 0xed, 0x78, 0x32, 0xc4, 0x36, 0x34, 0x14, 0x2c, 0xf7, 0x8c, 0x9c, 0xaf, 0x22,
	0x5b, 0xb7, 0xf0, 0x9d, 0x15, 0xf6, 0x1b, 0x58, 0xcb, 0x6f, 0x4d, 0xb2, 0x0f, 0xde, 0x91, 0x3e,
	0x79, 0x3b, 0x79, 0xa1, 0xb3, 0xb2, 0x53, 0xf8, 0x45, 0x81, 0x7d, 0x0d, 0xb5, 0x5e, 0x2c, 0x53,
	0xf5, 0x36, 0xbe, 0xb1, 0xf0, 0xda, 0xbc, 0x95, 0xf3, 0x44, 0xee, 0xb9, 0xd2, 0x59, 0x79, 0xfe,
	0xf5, 0x6f, 0x9f, 0x9e, 0x85, 0xe9, 0xf9, 0x64, 0xb8, 0xe7, 0xc7, 0x17, 0x8f, 0xc5, 0x65, 0x38,
	0x92, 0xb1, 0xff, 0x46, 0xa4, 0x8f, 0xe3, 0xb1, 0x88, 0x64, 0x14, 0xa6, 0xfe, 0xf9, 0x63, 0xf5,
	0x10, 0xf8, 0x78, 0x12, 0x3e, 0xce, 0x8c, 0x0c, 0x4d, 0x1a, 0x3d, 0xfd, 0x6f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x75, 0x95, 0x48, 0xf6, 0xa3, 0x17, 0x00, 0x00,
}
